import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";
import AppWrapper from "../components/App/AppWrapper";
import { useDispatch } from "react-redux";
import { SetUser } from "../redux/userSlice";
export default function Home() {
  const { data: session } = useSession();
  if (session) {
    const dispatch = useDispatch();
    dispatch(SetUser(session.user));
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AppWrapper />
      </>
    );
  }
  return (
    <>
      Not signed in <br />
      <button
        onClick={(e) => {
          e.preventDefault();
          signIn("cognito", {
            callbackUrl: process.env.NEXTAUTH_URL,
          });
        }}
      >
        Sign in
      </button>
    </>
  );
}
